FROM python:3.10

WORKDIR /app

RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash - &&\
    apt-get install nodejs

RUN npm i -g nodemon

ENTRYPOINT [ "nodemon", "-L",  "--exec" ]
CMD ["python3", "main.py" ]